include:
  - kafka/docker-compose.yml
  - clickhouse/docker-compose.yml


services:
  ugc:
    container_name: "ugc"
    build: ./flask_app
    env_file:
      - ./flask_app/src/.env
    expose:
      - 5000
    ports:
      - ${UGC_PORTS}
    networks:
      - ugc_service_network

  nginx:
    image: nginx:mainline-alpine3.18-perl
    volumes:
      - /tmp/logs/nginx/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - ugc
    ports:
      - 8080:80
    networks:
      - ugc_service_network

  ugc_etl:
    container_name: "ugc_etl"
    build: ./etl
    env_file:
      - ./etl/.env
    depends_on:
      kafka-0:
        condition: service_completed_successfully
      kafka-1:
        condition: service_completed_successfully
      kafka-2:
        condition: service_completed_successfully
    networks:
      - ugc_service_network

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - ugc_service_network

  logstash:
    image: logstash:8.10.2
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
      - "5045:5045/udp"
    volumes:
      - /tmp/logs/nginx/:/var/log/nginx/:ro
      - ./logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - ugc_service_network

  elasticsearch:
    image: elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    ports:
      - 9200:9200
    volumes:
      - elastic_elk:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://127.0.0.1:9200/_cat/health?h=status | grep -q yellow"]
      retries: 300
      interval: 10s
    networks:
      - ugc_service_network

  kibana:
    image: kibana:8.12.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ugc_service_network

  filebeat:
    image: elastic/filebeat:8.12.1
    volumes:
      - /tmp/logs/nginx:/var/log/nginx:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - ugc
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash
    # command: chmod go-w /usr/share/filebeat/filebeat.yml
    networks:
      - ugc_service_network


volumes:
  elastic_elk:
