name: UGC app

on:
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install mypy
          # pip install -r tests/requirements.txt
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # flake8 . --exit-zero --benchmark --format = pylint --output-file report.html 
          flake8 . --exit-zero --benchmark

      - name: Lint with mypy
        run: |
          mypy .

      # - name: Send Telegram Notification on Push Pull request
      #   uses: "appleboy/telegram-action@master"
      #   with:
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     to: ${{ secrets.TELEGRAM_CHAT_ID }}
      #     message: |
      #       New commit by ${{ github.actor }}!
      #       Commit: ${{ github.event.head_commit.message }}
      #       Repository: ${{ github.repository }}
      #       View changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
